spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.139.130:3306/guli_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:/mapper/ums/*.xml
  global-config:
    db-config:
      id-type: auto   #数据自增
server:
  port: 14000   #swagger 端口号
